query pageQuery {
  ...LayoutQueryFragment
}

query contentQuery($relativePath: String!) {
  ...LayoutQueryFragment
  page(relativePath: $relativePath) {
    ...PageParts
  }
}

query productQuery($relativePath: String!) {
  ...LayoutQueryFragment
  product(relativePath: $relativePath) {
    ...ProductParts
  }
}

query productsPublishedQuery {
  productConnection(filter: { isPublished: { eq: true } }) {
    edges {
      node {
        title
        description
        cover
        camera
        film
        id
        publishedAt
        isPublished
        seo {
          title
          description
        }
        isAvailable
        _sys {
          filename
        }
      }
    }
  }
}
